# 部署一百万个CI每天下库
name: CI

on:
  schedule:
  - cron: '11 4 * * 5,1,4'
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - run: |
        mkdir a
        cd a
        npm i sorted-containers
        cd ..
        sleep 5
        mkdir b
        cd b
        npm i sorted-containers
        cd ..
        sleep 5
        mkdir c
        cd c
        npm i sorted-containers
        cd ..
